export const isoCountries = [
  { code: 'DNK', name: 'Danmark' },
  { code: 'AFG', name: 'Afghanistan' },
  { code: 'ALB', name: 'Albanien' },
  { code: 'DZA', name: 'Algeriet' },
  { code: 'ASM', name: 'Amerikansk Samoa' },
  { code: 'AND', name: 'Andorra' },
  { code: 'AGO', name: 'Angola' },
  { code: 'ATA', name: 'Antarktis' },
  { code: 'ATG', name: 'Antigua og Barbuda' },
  { code: 'ARG', name: 'Argentina' },
  { code: 'ARM', name: 'Armenien' },
  { code: 'AZE', name: 'Aserbajdsjan' },
  { code: 'AUS', name: 'Australien' },
  { code: 'BHR', name: 'Bahrain' },
  { code: 'BGD', name: 'Bangladesh' },
  { code: 'BRB', name: 'Barbados' },
  { code: 'BEL', name: 'Belgien' },
  { code: 'BLZ', name: 'Belize' },
  { code: 'BEN', name: 'Benin' },
  { code: 'BTN', name: 'Bhutan' },
  { code: 'BOL', name: 'Bolivia' },
  { code: 'BIH', name: 'Bosnien-Hercegovina' },
  { code: 'BWA', name: 'Botswana' },
  { code: 'BRA', name: 'Brasilien' },
  { code: 'BRN', name: 'Brunei' },
  { code: 'BGR', name: 'Bulgarien' },
  { code: 'BFA', name: 'Burkina Faso' },
  { code: 'BDI', name: 'Burundi' },
  { code: 'KHM', name: 'Cambodja' },
  { code: 'CMR', name: 'Cameroun' },
  { code: 'CAN', name: 'Canada' },
  { code: 'BES', name: 'Caribiske Nederlandene' },
  { code: 'CAF', name: 'Centralafrikanske Republik' },
  { code: 'CHL', name: 'Chile' },
  { code: 'CCK', name: 'Cocosøerne' },
  { code: 'COL', name: 'Colombia' },
  { code: 'COM', name: 'Comorerne' },
  { code: 'COG', name: 'Congo' },
  { code: 'COK', name: 'Cookøerne' },
  { code: 'CRI', name: 'Costa Rica' },
  { code: 'CUW', name: 'Curacao' },
  { code: 'CYP', name: 'Cypern' },
  { code: 'DOM', name: 'Den Dominikanske Republik' },
  { code: 'DJI', name: 'Djibouti' },
  { code: 'DMA', name: 'Dominica' },
  { code: 'ECU', name: 'Ecuador' },
  { code: 'EGY', name: 'Egypten' },
  { code: 'SLV', name: 'El Salvador' },
  { code: 'CIV', name: 'Elfenbenskysten' },
  { code: 'ERI', name: 'Eritrea' },
  { code: 'EST', name: 'Estland' },
  { code: 'SWZ', name: 'Eswatini' },
  { code: 'ETH', name: 'Etiopien' },
  { code: 'FJI', name: 'Fiji' },
  { code: 'PHL', name: 'Filippinerne' },
  { code: 'FIN', name: 'Finland' },
  { code: 'ARE', name: 'Forenede Arabiske Emirater' },
  { code: 'FRA', name: 'Frankrig' },
  { code: 'PYF', name: 'Fransk Polynesien' },
  { code: 'GAB', name: 'Gabon' },
  { code: 'GMB', name: 'Gambia' },
  { code: 'GEO', name: 'Georgien' },
  { code: 'GHA', name: 'Ghana' },
  { code: 'GRC', name: 'Grækenland' },
  { code: 'GRD', name: 'Grenada' },
  { code: 'GUM', name: 'Guam' },
  { code: 'GTM', name: 'Guatemala' },
  { code: 'GGY', name: 'Guernsey' },
  { code: 'GIN', name: 'Guinea' },
  { code: 'GNB', name: 'Guinea-Bissau' },
  { code: 'GUY', name: 'Guyana' },
  { code: 'HTI', name: 'Haiti' },
  { code: 'HMD', name: 'Heard-øen' },
  { code: 'HND', name: 'Honduras' },
  { code: 'BLR', name: 'Hviderusland' },
  { code: 'IND', name: 'Indien' },
  { code: 'IDN', name: 'Indonesien' },
  { code: 'IRQ', name: 'Irak' },
  { code: 'IRL', name: 'Irland' },
  { code: 'ISL', name: 'Island' },
  { code: 'IMN', name: 'Isle of Man' },
  { code: 'ISR', name: 'Israel' },
  { code: 'ITA', name: 'Italien' },
  { code: 'JAM', name: 'Jamaica' },
  { code: 'JPN', name: 'Japan' },
  { code: 'JOR', name: 'Jordan' },
  { code: 'KAZ', name: 'Kasakhstan' },
  { code: 'KEN', name: 'Kenya' },
  { code: 'CHN', name: 'Kina' },
  { code: 'KGZ', name: 'Kirgisistan' },
  { code: 'KIR', name: 'Kiribati' },
  { code: 'HRV', name: 'Kroatien' },
  { code: 'KWT', name: 'Kuwait' },
  { code: 'LAO', name: 'Laos' },
  { code: 'LSO', name: 'Lesotho' },
  { code: 'LVA', name: 'Letland' },
  { code: 'LBN', name: 'Libanon' },
  { code: 'LBR', name: 'Liberia' },
  { code: 'LBY', name: 'Libyen' },
  { code: 'LIE', name: 'Liechtenstein' },
  { code: 'LTU', name: 'Litauen' },
  { code: 'LUX', name: 'Luxembourg' },
  { code: 'MDG', name: 'Madagaskar' },
  { code: 'MKD', name: 'Nordmakedonien' },
  { code: 'MWI', name: 'Malawi' },
  { code: 'MDV', name: 'Maldiverne' },
  { code: 'MYS', name: 'Malaysia' },
  { code: 'MLI', name: 'Mali' },
  { code: 'MLT', name: 'Malta' },
  { code: 'MAR', name: 'Marokko' },
  { code: 'MHL', name: 'Marshalløerne' },
  { code: 'MTQ', name: 'Martinique' },
  { code: 'MRT', name: 'Mauretanien' },
  { code: 'MUS', name: 'Mauritius' },
  { code: 'MEX', name: 'Mexico' },
  { code: 'FSM', name: 'Mikronesien' },
  { code: 'MDA', name: 'Moldova' },
  { code: 'MCO', name: 'Monaco' },
  { code: 'MNG', name: 'Mongoliet' },
  { code: 'MNE', name: 'Montenegro' },
  { code: 'MSR', name: 'Montserrat' },
  { code: 'MOZ', name: 'Mozambique' },
  { code: 'MMR', name: 'Myanmar' },
  { code: 'NAM', name: 'Namibia' },
  { code: 'NRU', name: 'Nauru' },
  { code: 'NPL', name: 'Nepal' },
  { code: 'NZL', name: 'New Zealand' },
  { code: 'NIC', name: 'Nicaragua' },
  { code: 'NER', name: 'Niger' },
  { code: 'NGA', name: 'Nigeria' },
  { code: 'NIU', name: 'Niue' },
  { code: 'PRK', name: 'Nordkorea' },
  { code: 'NOR', name: 'Norge' },
  { code: 'NCL', name: 'Ny Kaledonien' },
  { code: 'OMN', name: 'Oman' },
  { code: 'PAK', name: 'Pakistan' },
  { code: 'PLW', name: 'Palau' },
  { code: 'PSE', name: 'Palæstina' },
  { code: 'PAN', name: 'Panama' },
  { code: 'PNG', name: 'Papua Ny Guinea' },
  { code: 'PRY', name: 'Paraguay' },
  { code: 'PER', name: 'Peru' },
  { code: 'PCN', name: 'Pitcairn' },
  { code: 'POL', name: 'Polen' },
  { code: 'PRT', name: 'Portugal' },
  { code: 'PRI', name: 'Puerto Rico' },
  { code: 'QAT', name: 'Qatar' },
  { code: 'ROU', name: 'Rumænien' },
  { code: 'RUS', name: 'Rusland' },
  { code: 'RWA', name: 'Rwanda' },
  { code: 'REU', name: 'Réunion' },
  { code: 'BLM', name: 'Saint Barthélemy' },
  { code: 'SHN', name: 'Saint Helena' },
  { code: 'KNA', name: 'Saint Kitts og Nevis' },
  { code: 'LCA', name: 'Saint Lucia' },
  { code: 'MAF', name: 'Saint Martin' },
  { code: 'SPM', name: 'Saint Pierre og Miquelon' },
  { code: 'VCT', name: 'Saint Vincent og Grenadinerne' },
  { code: 'WSM', name: 'Samoa' },
  { code: 'SMR', name: 'San Marino' },
  { code: 'STP', name: 'São Tomé og Príncipe' },
  { code: 'SAU', name: 'Saudi-Arabien' },
  { code: 'CHE', name: 'Schweiz' },
  { code: 'SEN', name: 'Senegal' },
  { code: 'SRB', name: 'Serbien' },
  { code: 'SYC', name: 'Seychellerne' },
  { code: 'SLE', name: 'Sierra Leone' },
  { code: 'SGP', name: 'Singapore' },
  { code: 'SVK', name: 'Slovakiet' },
  { code: 'SVN', name: 'Slovenien' },
  { code: 'SLB', name: 'Salomonøerne' },
  { code: 'SOM', name: 'Somalia' },
  { code: 'ESP', name: 'Spanien' },
  { code: 'LKA', name: 'Sri Lanka' },
  { code: 'GBR', name: 'Storbritannien' },
  { code: 'SDN', name: 'Sudan' },
  { code: 'SUR', name: 'Surinam' },
  { code: 'SWE', name: 'Sverige' },
  { code: 'SYR', name: 'Syrien' },
  { code: 'ZAF', name: 'Sydafrika' },
  { code: 'KOR', name: 'Sydkorea' },
  { code: 'SSD', name: 'Sydsudan' },
  { code: 'TJK', name: 'Tadsjikistan' },
  { code: 'TWN', name: 'Taiwan' },
  { code: 'TZA', name: 'Tanzania' },
  { code: 'THA', name: 'Thailand' },
  { code: 'TGO', name: 'Togo' },
  { code: 'TKL', name: 'Tokelau' },
  { code: 'TON', name: 'Tonga' },
  { code: 'TTO', name: 'Trinidad og Tobago' },
  { code: 'TCD', name: 'Tchad' },
  { code: 'CZE', name: 'Tjekkiet' },
  { code: 'TUN', name: 'Tunesien' },
  { code: 'TKM', name: 'Turkmenistan' },
  { code: 'TCA', name: 'Turks- og Caicosøerne' },
  { code: 'TUV', name: 'Tuvalu' },
  { code: 'TUR', name: 'Tyrkiet' },
  { code: 'DEU', name: 'Tyskland' },
  { code: 'UGA', name: 'Uganda' },
  { code: 'UKR', name: 'Ukraine' },
  { code: 'HUN', name: 'Ungarn' },
  { code: 'URY', name: 'Uruguay' },
  { code: 'USA', name: 'USA' },
  { code: 'UZB', name: 'Usbekistan' },
  { code: 'VUT', name: 'Vanuatu' },
  { code: 'VAT', name: 'Vatikanstaten' },
  { code: 'VEN', name: 'Venezuela' },
  { code: 'ESH', name: 'Vestsahara' },
  { code: 'VNM', name: 'Vietnam' },
  { code: 'WLF', name: 'Wallis og Futuna' },
  { code: 'YEM', name: 'Yemen' },
  { code: 'ZMB', name: 'Zambia' },
  { code: 'ZWE', name: 'Zimbabwe' },
  { code: 'AUT', name: 'Østrig' },
] as const;

export type IsoCountry = (typeof isoCountries)[number];
export type IsoCountryCode = IsoCountry['code'];

export const languageCodes = {
  da: '1009', // Dansk
  en: '1001', // Engelsk
  de: '1031', // Tysk
  sv: '1053', // Svensk
  no: '1044', // Norsk
  fi: '1035', // Finsk
  fr: '1036', // Fransk
  es: '1034', // Spansk
  it: '1040', // Italiensk
  nl: '1043', // Hollandsk
  pl: '1045', // Polsk
  pt: '1046', // Portugisisk
  ru: '1049', // Russisk
  ar: '1025', // Arabisk
  zh: '2052', // Kinesisk
  ja: '1041', // Japansk
  ko: '1042', // Koreansk
} as const;

export type LanguageCode = keyof typeof languageCodes;
export type LanguageNumericCode = (typeof languageCodes)[LanguageCode];

export const geoLocations = [
  { value: '2208', text: 'Danmark' },
  { value: '2004', text: 'Afghanistan' },
  { value: '2008', text: 'Albanien' },
  { value: '2012', text: 'Algeriet' },
  { value: '2016', text: 'Amerikansk Samoa' },
  { value: '2020', text: 'Andorra' },
  { value: '2024', text: 'Angola' },
  { value: '2010', text: 'Antarktis' },
  { value: '2028', text: 'Antigua og Barbuda' },
  { value: '2032', text: 'Argentina' },
  { value: '2051', text: 'Armenien' },
  { value: '2031', text: 'Aserbajdsjan' },
  { value: '2036', text: 'Australien' },
  { value: '2048', text: 'Bahrain' },
  { value: '2050', text: 'Bangladesh' },
  { value: '2052', text: 'Barbados' },
  { value: '2056', text: 'Belgien' },
  { value: '2084', text: 'Belize' },
  { value: '2204', text: 'Benin' },
  { value: '2064', text: 'Bhutan' },
  { value: '2068', text: 'Bolivia' },
  { value: '2070', text: 'Bosnien-Hercegovina' },
  { value: '2072', text: 'Botswana' },
  { value: '2076', text: 'Brasilien' },
  { value: '2096', text: 'Brunei' },
  { value: '2100', text: 'Bulgarien' },
  { value: '2854', text: 'Burkina Faso' },
  { value: '2108', text: 'Burundi' },
  { value: '2116', text: 'Cambodja' },
  { value: '2120', text: 'Cameroun' },
  { value: '2124', text: 'Canada' },
  { value: '2535', text: 'Caribiske Nederlandene' },
  { value: '2140', text: 'Centralafrikanske Republik' },
  { value: '2152', text: 'Chile' },
  { value: '2166', text: 'Cocosøerne' },
  { value: '2170', text: 'Colombia' },
  { value: '2174', text: 'Comorerne' },
  { value: '2180', text: 'Congo' },
  { value: '2184', text: 'Cookøerne' },
  { value: '2188', text: 'Costa Rica' },
  { value: '2531', text: 'Curacao' },
  { value: '2196', text: 'Cypern' },
  { value: '2214', text: 'Den Dominikanske Republik' },
  { value: '2262', text: 'Djibouti' },
  { value: '2212', text: 'Dominica' },
  { value: '2218', text: 'Ecuador' },
  { value: '2818', text: 'Egypten' },
  { value: '2222', text: 'El Salvador' },
  { value: '2384', text: 'Elfenbenskysten' },
  { value: '2232', text: 'Eritrea' },
  { value: '2233', text: 'Estland' },
  { value: '2748', text: 'Eswatini' },
  { value: '2231', text: 'Etiopien' },
  { value: '2242', text: 'Fiji' },
  { value: '2608', text: 'Filippinerne' },
  { value: '2246', text: 'Finland' },
  { value: '2784', text: 'Forenede Arabiske Emirater' },
  { value: '2250', text: 'Frankrig' },
  { value: '2258', text: 'Fransk Polynesien' },
  { value: '2266', text: 'Gabon' },
  { value: '2270', text: 'Gambia' },
  { value: '2268', text: 'Georgien' },
  { value: '2288', text: 'Ghana' },
  { value: '2300', text: 'Grækenland' },
  { value: '2308', text: 'Grenada' },
  { value: '2316', text: 'Guam' },
  { value: '2320', text: 'Guatemala' },
  { value: '2831', text: 'Guernsey' },
  { value: '2324', text: 'Guinea' },
  { value: '2624', text: 'Guinea-Bissau' },
  { value: '2328', text: 'Guyana' },
  { value: '2332', text: 'Haiti' },
  { value: '2334', text: 'Heard-øen' },
  { value: '2340', text: 'Honduras' },
  { value: '2112', text: 'Hviderusland' },
  { value: '2356', text: 'Indien' },
  { value: '2360', text: 'Indonesien' },
  { value: '2368', text: 'Irak' },
  { value: '2372', text: 'Irland' },
  { value: '2352', text: 'Island' },
  { value: '2833', text: 'Isle of Man' },
  { value: '2376', text: 'Israel' },
  { value: '2380', text: 'Italien' },
  { value: '2388', text: 'Jamaica' },
  { value: '2392', text: 'Japan' },
  { value: '2832', text: 'Jersey' },
  { value: '2400', text: 'Jordan' },
  { value: '2162', text: 'Juleøen' },
  { value: '2132', text: 'Kap Verde' },
  { value: '2398', text: 'Kasakhstan' },
  { value: '2404', text: 'Kenya' },
  { value: '2156', text: 'Kina' },
  { value: '2417', text: 'Kirgisistan' },
  { value: '2296', text: 'Kiribati' },
  { value: '2191', text: 'Kroatien' },
  { value: '2414', text: 'Kuwait' },
  { value: '2418', text: 'Laos' },
  { value: '2426', text: 'Lesotho' },
  { value: '2428', text: 'Letland' },
  { value: '2422', text: 'Libanon' },
  { value: '2430', text: 'Liberia' },
  { value: '2434', text: 'Libya' },
  { value: '2438', text: 'Liechtenstein' },
  { value: '2440', text: 'Litauen' },
  { value: '2442', text: 'Luxembourg' },
  { value: '2450', text: 'Madagaskar' },
  { value: '2454', text: 'Malawi' },
  { value: '2458', text: 'Malaysia' },
  { value: '2462', text: 'Maldiverne' },
  { value: '2466', text: 'Mali' },
  { value: '2470', text: 'Malta' },
  { value: '2504', text: 'Marokko' },
  { value: '2584', text: 'Marshalløerne' },
  { value: '2478', text: 'Mauretanien' },
  { value: '2480', text: 'Mauritius' },
  { value: '2484', text: 'Mexico' },
  { value: '2583', text: 'Mikronesien' },
  { value: '2498', text: 'Moldova' },
  { value: '2492', text: 'Monaco' },
  { value: '2496', text: 'Mongoliet' },
  { value: '2499', text: 'Montenegro' },
  { value: '2508', text: 'Mozambique' },
  { value: '2104', text: 'Myanmar (Burma)' },
  { value: '2516', text: 'Namibia' },
  { value: '2520', text: 'Nauru' },
  { value: '2528', text: 'Nederlandene' },
  { value: '2524', text: 'Nepal' },
  { value: '2554', text: 'New Zealand' },
  { value: '2558', text: 'Nicaragua' },
  { value: '2562', text: 'Niger' },
  { value: '2566', text: 'Nigeria' },
  { value: '2570', text: 'Niue' },
  { value: '2807', text: 'Nordmakedonien' },
  { value: '2580', text: 'Nordmarianerne' },
  { value: '2574', text: 'Norfolk Island' },
  { value: '2578', text: 'Norge' },
  { value: '2540', text: 'Ny Kaledonien' },
  { value: '2512', text: 'Oman' },
  { value: '2040', text: 'Østrig' },
  { value: '2586', text: 'Pakistan' },
  { value: '2585', text: 'Palau' },
  { value: '2591', text: 'Panama' },
  { value: '2598', text: 'Papua Ny Guinea' },
  { value: '2600', text: 'Paraguay' },
  { value: '2604', text: 'Peru' },
  { value: '2612', text: 'Pitcairn-øerne' },
  { value: '2616', text: 'Polen' },
  { value: '2620', text: 'Portugal' },
  { value: '2634', text: 'Qatar' },
  { value: '2178', text: 'Republikken Congo' },
  { value: '2642', text: 'Rumænien' },
  { value: '2643', text: 'Rusland' },
  { value: '2646', text: 'Rwanda' },
  { value: '2652', text: 'Saint Barthelemy' },
  { value: '2654', text: 'Saint Helena' },
  { value: '2659', text: 'Saint Kitts og Nevis' },
  { value: '2662', text: 'Saint Lucia' },
  { value: '2663', text: 'Saint Martin' },
  { value: '2666', text: 'Saint Pierre' },
  { value: '2670', text: 'Saint Vincent' },
  { value: '2090', text: 'Salomonøerne' },
  { value: '2882', text: 'Samoa' },
  { value: '2674', text: 'San Marino' },
  { value: '2678', text: 'Sao Tome og Principe' },
  { value: '2682', text: 'Saudi-Arabien' },
  { value: '2756', text: 'Schweiz' },
  { value: '2686', text: 'Senegal' },
  { value: '2688', text: 'Serbien' },
  { value: '2690', text: 'Seychellerne' },
  { value: '2694', text: 'Sierra Leone' },
  { value: '2702', text: 'Singapore' },
  { value: '2534', text: 'Sint Maarten' },
  { value: '2703', text: 'Slovakiet' },
  { value: '2705', text: 'Slovenien' },
  { value: '2706', text: 'Somalia' },
  { value: '2724', text: 'Spanien' },
  { value: '2144', text: 'Sri Lanka' },
  { value: '2826', text: 'Storbritannien' },
  { value: '2736', text: 'Sudan' },
  { value: '2740', text: 'Surinam' },
  { value: '2752', text: 'Sverige' },
  { value: '2710', text: 'Sydafrika' },
  { value: '2239', text: 'Sydgeorgien' },
  { value: '2410', text: 'Sydkorea' },
  { value: '2728', text: 'Sydsudan' },
  { value: '2762', text: 'Tadsjikistan' },
  { value: '2834', text: 'Tanzania' },
  { value: '2148', text: 'Tchad' },
  { value: '2764', text: 'Thailand' },
  { value: '2044', text: 'The Bahamas' },
  { value: '2626', text: 'Timor-Leste' },
  { value: '2203', text: 'Tjekkiet' },
  { value: '2768', text: 'Togo' },
  { value: '2772', text: 'Tokelau' },
  { value: '2776', text: 'Tonga' },
  { value: '2780', text: 'Trinidad og Tobago' },
  { value: '2788', text: 'Tunesien' },
  { value: '2795', text: 'Turkmenistan' },
  { value: '2798', text: 'Tuvalu' },
  { value: '2792', text: 'Tyrkiet' },
  { value: '2276', text: 'Tyskland' },
  { value: '2800', text: 'Uganda' },
  { value: '2804', text: 'Ukraine' },
  { value: '2348', text: 'Ungarn' },
  { value: '2858', text: 'Uruguay' },
  { value: '2840', text: 'USA' },
  { value: '2860', text: 'Usbekistan' },
  { value: '2548', text: 'Vanuatu' },
  { value: '2336', text: 'Vatikanstaten' },
  { value: '2862', text: 'Venezuela' },
  { value: '2704', text: 'Vietnam' },
  { value: '2876', text: 'Wallis og Futuna' },
  { value: '2887', text: 'Yemen' },
  { value: '2894', text: 'Zambia' },
  { value: '2716', text: 'Zimbabwe' },
  { value: '2226', text: 'Ækvatorialguinea' },
] as const;

export type GeoLocation = (typeof geoLocations)[number];
export type GeoLocationValue = GeoLocation['value'];

// Function to convert ISO alpha-3 to alpha-2 country codes
export const convertToAlpha2 = (alpha3: string): string => {
  const alpha3ToAlpha2: { [key: string]: string } = {
    DNK: 'DK',
    AFG: 'AF',
    ALB: 'AL',
    DZA: 'DZ',
    ASM: 'AS',
    AND: 'AD',
    AGO: 'AO',
    ATA: 'AQ',
    ATG: 'AG',
    ARG: 'AR',
    ARM: 'AM',
    AZE: 'AZ',
    AUS: 'AU',
    BHR: 'BH',
    BGD: 'BD',
    BRB: 'BB',
    BEL: 'BE',
    BLZ: 'BZ',
    BEN: 'BJ',
    BTN: 'BT',
    BOL: 'BO',
    BIH: 'BA',
    BWA: 'BW',
    BRA: 'BR',
    BRN: 'BN',
    BGR: 'BG',
    BFA: 'BF',
    BDI: 'BI',
    KHM: 'KH',
    CMR: 'CM',
    CAN: 'CA',
    BES: 'BQ',
    CAF: 'CF',
    CHL: 'CL',
    CHN: 'CN',
    CCK: 'CC',
    COL: 'CO',
    COM: 'KM',
    COG: 'CG',
    COK: 'CK',
    CRI: 'CR',
    CUW: 'CW',
    CYP: 'CY',
    DOM: 'DO',
    DJI: 'DJ',
    DMA: 'DM',
    ECU: 'EC',
    EGY: 'EG',
    SLV: 'SV',
    CIV: 'CI',
    ERI: 'ER',
    EST: 'EE',
    SWZ: 'SZ',
    ETH: 'ET',
    FJI: 'FJ',
    PHL: 'PH',
    FIN: 'FI',
    ARE: 'AE',
    FRA: 'FR',
    PYF: 'PF',
    GAB: 'GA',
    GMB: 'GM',
    GEO: 'GE',
    GHA: 'GH',
    GRC: 'GR',
    GRD: 'GD',
    GUM: 'GU',
    GTM: 'GT',
    GGY: 'GG',
    GIN: 'GN',
    GNB: 'GW',
    GUY: 'GY',
    HTI: 'HT',
    HMD: 'HM',
    HND: 'HN',
    BLR: 'BY',
    IND: 'IN',
    IDN: 'ID',
    IRQ: 'IQ',
    IRL: 'IE',
    ISL: 'IS',
    IMN: 'IM',
    ISR: 'IL',
    ITA: 'IT',
    JAM: 'JM',
    JPN: 'JP',
    JOR: 'JO',
    KAZ: 'KZ',
    KEN: 'KE',
    KGZ: 'KG',
    KIR: 'KI',
    HRV: 'HR',
    KWT: 'KW',
    LAO: 'LA',
    LSO: 'LS',
    LVA: 'LV',
    LBN: 'LB',
    LBR: 'LR',
    LBY: 'LY',
    LIE: 'LI',
    LTU: 'LT',
    LUX: 'LU',
    MDG: 'MG',
    MKD: 'MK',
    MWI: 'MW',
    MDV: 'MV',
    MYS: 'MY',
    MLI: 'ML',
    MLT: 'MT',
    MAR: 'MA',
    MHL: 'MH',
    MTQ: 'MQ',
    MRT: 'MR',
    MUS: 'MU',
    MEX: 'MX',
    FSM: 'FM',
    MDA: 'MD',
    MCO: 'MC',
    MNG: 'MN',
    MNE: 'ME',
    MSR: 'MS',
    MOZ: 'MZ',
    MMR: 'MM',
    NAM: 'NA',
    NRU: 'NR',
    NPL: 'NP',
    NZL: 'NZ',
    NIC: 'NI',
    NER: 'NE',
    NGA: 'NG',
    NIU: 'NU',
    PRK: 'KP',
    NOR: 'NO',
    NCL: 'NC',
    OMN: 'OM',
    PAK: 'PK',
    PLW: 'PW',
    PSE: 'PS',
    PAN: 'PA',
    PNG: 'PG',
    PRY: 'PY',
    PER: 'PE',
    PCN: 'PN',
    POL: 'PL',
    PRT: 'PT',
    PRI: 'PR',
    QAT: 'QA',
    ROU: 'RO',
    RUS: 'RU',
    RWA: 'RW',
    REU: 'RE',
    BLM: 'BL',
    SHN: 'SH',
    KNA: 'KN',
    LCA: 'LC',
    MAF: 'MF',
    SPM: 'PM',
    VCT: 'VC',
    WSM: 'WS',
    SMR: 'SM',
    STP: 'ST',
    SAU: 'SA',
    CHE: 'CH',
    SEN: 'SN',
    SRB: 'RS',
    SYC: 'SC',
    SLE: 'SL',
    SGP: 'SG',
    SVK: 'SK',
    SVN: 'SI',
    SLB: 'SB',
    SOM: 'SO',
    ESP: 'ES',
    LKA: 'LK',
    GBR: 'GB',
    SDN: 'SD',
    SUR: 'SR',
    SWE: 'SE',
    SYR: 'SY',
    ZAF: 'ZA',
    KOR: 'KR',
    SSD: 'SS',
    TJK: 'TJ',
    TWN: 'TW',
    TZA: 'TZ',
    THA: 'TH',
    TGO: 'TG',
    TKL: 'TK',
    TON: 'TO',
    TTO: 'TT',
    TCD: 'TD',
    CZE: 'CZ',
    TUN: 'TN',
    TKM: 'TM',
    TCA: 'TC',
    TUV: 'TV',
    TUR: 'TR',
    DEU: 'DE',
    UGA: 'UG',
    UKR: 'UA',
    HUN: 'HU',
    URY: 'UY',
    USA: 'US',
    UZB: 'UZ',
    VUT: 'VU',
    VAT: 'VA',
    VEN: 'VE',
    ESH: 'EH',
    VNM: 'VN',
    WLF: 'WF',
    YEM: 'YE',
    ZMB: 'ZM',
    ZWE: 'ZW',
    AUT: 'AT',
  };

  return alpha3ToAlpha2[alpha3] || alpha3;
};
